name: log artefact
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "ca marche ?"
      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run build

      - name: npm test
        run: npm test

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format-check

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'log'
          path: logs.txt
